# Generated by Django 5.0.7 on 2024-09-27 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comics',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='figuras',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='libros',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mangas',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
